### ISSUE TITLE
Request: add uploadStream support

### ISSUE THREAD

**Issue by dsaintbase1** [yclgkd/strapi-provider-upload-tencent-cloud-storage#1]
## Metadata
Strapi version: 4.14.2
Plugin version: 1.1.4 
Node version: 18.18.2
Command ran to start the service: `node --trace-warnings /opt/node_modules/@strapi/strapi/bin/strapi.js start`

Plugin config:
```
module.exports = ({ env }) => ({
  // ...
  upload: {
    config: {
      provider: "strapi-provider-upload-tencent-cloud-storage",
      providerOptions: {
        SecretId: env("COS_SECRETID"),
        SecretKey: env("COS_SECRETKEY"),
        Region: env("COS_REGION"),
        Bucket: env("COS_BUCKET"),
      },
    },
  },
  // ...
});
```
Content of the environment variables:
```
COS_SECRETID="not-set"
COS_SECRETKEY="not-set"
COS_REGION="ap-shanghai"
COS_BUCKET="XXXXX"
```
## Issue
The `strapi-provider-upload-tencent-cloud-storage` plugin isn't getting loaded at startup time of Strapi. It falls back to the default upload method.
We see this message when starting the service regarding the `uploadStream` feature: 
```
(node:1) Warning: The upload provider "strapi-provider-upload-tencent-cloud-storage" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.
    at createProvider (/opt/node_modules/@strapi/plugin-upload/server/register.js:73:13)
    at module.exports [as register] (/opt/node_modules/@strapi/plugin-upload/server/register.js:16:38)
    at Object.register (/opt/node_modules/@strapi/strapi/dist/core/domain/module/index.js:49:52)
    at Object.register (/opt/node_modules/@strapi/strapi/dist/core/registries/modules.js:29:27)
    at async Strapi.runLifecyclesFunctions (/opt/node_modules/@strapi/strapi/dist/Strapi.js:509:9)
    at async Strapi.register (/opt/node_modules/@strapi/strapi/dist/Strapi.js:428:9)
    at async Strapi.load (/opt/node_modules/@strapi/strapi/dist/Strapi.js:493:9)
    at async Strapi.start (/opt/node_modules/@strapi/strapi/dist/Strapi.js:273:17)
```

I noticed that the feature was still enabled in `strapi-provider-upload-tencent-cloud-storage@1.1.1` so I tried that version and got this issue when trying to upload a media. The credentials are not set at the moment (I've set placeholders), but I wanted to share the output as it's not obvious to me on what it's reporting:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
<img width="844" alt="Screenshot 2023-10-19 at 21 14 27" src="https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/148466256/2f05f2a2-cbad-4765-95bc-b78aa753bfb4">

Let me know if you need more info. Thanks!

**Comment by yclgkd** [comment]
I haven't been able to reproduce the issue of uploading images failing temporarily. The "uploadStream" method you mentioned is not the key factor in the problem; it's just a warning. Without this method, the upload function will fall back to the "upload" function. Your environment variables and plugin configuration are fine, but I can't confirm if your "SecretId" and "SecretKey" are correct.

I suggest you try using [COSBrowser](https://www.tencentcloud.com/document/product/436/32565) to see if you can log in to the object storage and upload images after filling in the "SecretId" and "SecretKey" configurations.

![image](https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/31514100/f90d2548-deee-4fbf-adf7-561e672901e9)

In addition, to correctly display images in the Strapi media library, you also need to configure [middleware](https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage#security-middleware-configuration).

**Comment by dsaintbase1** [comment]
Hey again.

Thanks for the advise. I've ignored the uploadStream warning & I can now upload images after setting up the authentication.
But even after adding the middleware security configuration, I still cannot display the images in the app.

Am I missing something here?

```
#  -> middlewares.js

module.exports = [
  'strapi::errors',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "<COS_BUCKET>.cos.<COS_REGION>.myqcloud.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "<COS_BUCKET>.cos.<COS_REGION>.myqcloud.com",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];

```
<img width="845" alt="Screenshot 2023-10-20 at 14 43 56" src="https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/148466256/f457aa96-1e32-4a51-b581-8f4af3a46b35">
<img width="988" alt="Screenshot 2023-10-20 at 14 43 50" src="https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/148466256/624e3c1d-60f5-4b5a-9d1c-b25669d2ef9b">
<img width="696" alt="Screenshot 2023-10-20 at 14 54 20" src="https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/148466256/d9449a79-d452-4bff-925e-33eba6fe473c">

**Comment by yclgkd** [comment]
Your configuration is correct; I think you should check the permissions of the object storage to ensure it's publicly readable and privately writable. 
If your bucket is configured to be private, you will need to set the ACL option to private in the params object. This will ensure file URLs are signed.

**Comment by dsaintbase1** [comment]
The bucket I'm using is private. 
I've set the ACL to private in the plugin params; the result is still the same for image preview.

What would you recommend to troubleshoot & verify if the file URLs are signed?

**Comment by dsaintbase1** [comment]
Nevermind, I got it to work. The issue was on my side:
![2023-10-21_18-49](https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/148466256/6118933c-3db2-4b2b-ae55-c41e3e57ba4a)

Thanks for your help & good work with this plugin!
