### ISSUE TITLE
配置了CDN域名，但是请求返回中，为什么还是COS桶的域名呢？

### ISSUE THREAD

**Issue by sfyang2** [yclgkd/strapi-provider-upload-tencent-cloud-storage#2]
<img width="1148" alt="image" src="https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage/assets/46621212/972ae473-d38e-473f-9b10-93eed4948a69">

**Comment by yclgkd** [comment]
如果是在配置了 CDN 域名前上传的图片就还是会显示对象存储地址，但是我不确定图中是不是这个问题，可以先排查一下。另外可以贴一下你的插件配置和环境变量么（⚠️注意打码一些重要内容，如密钥等信息）

**Comment by yclgkd** [comment]
I will close this issue because it has not received a response for a long time.
