### ISSUE TITLE
Apply CDN domain to images uploaded before configuring the feature.

### ISSUE THREAD

**Issue by dsaintbase1** [yclgkd/strapi-provider-upload-tencent-cloud-storage#3]
Hi,

I'm working on setting up the CDN feature in the [strapi-provider-upload-tencent-cloud-storage](https://github.com/yclgkd/strapi-provider-upload-tencent-cloud-storage) plugin in order to pull images from a publicly available URL.

Example of the URL I'm seeing by inspecting the strapi database:
```
mysql> select url from files;
+---------------------------------------------------------------------------------------------------+
| url                                                                                               |
+---------------------------------------------------------------------------------------------------+
| https://bucket-url*.myqcloud.com/default_avatar.png |
| https://bucket-url*.myqcloud.com/gif_aaf93c6e3a.gif            |
| https://cdn-url/media/2024_01_31_10_54_ea250fb1b2.png                               |
+---------------------------------------------------------------------------------------------------+
```

After running some tests locally, the issue we're facing is that the URL for the images that were uploaded before setting the CDN domain still points to the domain of the bucket finishing with *myqcloud.com.

Is there a way to ensure that all the images now points to the CDN domain no matter when they were uploaded?

Thanks

**Comment by yclgkd** [comment]
I think you can solve it in two ways: one is to try to modify the original URL address through middleware, and the other is to update the URL in the database through a script. It is important to note that if you choose the second method, you must ensure proper data backup.

This link might be useful to you: https://docs.strapi.io/dev-docs/backend-customization/middlewares

**Comment by dsaintbase1** [comment]
I've modified the URLs in the database. by manually running some SQL commands.
Thanks.
