### ISSUE TITLE
node version issue

### ISSUE THREAD

**Issue by zjy365** [yclgkd/strapi-provider-upload-tencent-cloud-storage#5]
error strapi-provider-upload-tencent-cloud-storage@1.1.4: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=19.x.x". Got "20.4.0"
error Found incompatible module.

**Comment by yclgkd** [comment]
This issue has been solved, please update `strapi-provider-upload-tencent-cloud-storage` to `1.1.5`.

**Comment by zjy365** [comment]
Thank you very much for your prompt response.
